// User Actions
export const GET_USERS_LIST_REQUESTED = 'GET_USERS_LIST_REQUESTED';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAILED = 'GET_USERS_LIST_FAILED';

export const ADD_USERS_REQUESTED = 'ADD_USERS_REQUESTED';
export const ADD_USERS_SUCCESS = 'ADD_USERS_SUCCESS';
export const ADD_USERS_FAILED = 'ADD_USERS_FAILED';

export const DELETE_USERS_REQUESTED = 'DELETE_USERS_REQUESTED';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAILED = 'DELETE_USERS_FAILED';

export const UPDATE_USERS_REQUESTED = 'UPDATE_USERS_REQUESTED';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_FAILED = 'UPDATE_USERS_FAILED';

// Branch Actions
export const GET_BRANCH_LIST_REQUESTED = 'GET_BRANCH_LIST_REQUESTED';
export const GET_BRANCH_LIST_SUCCESS = 'GET_BRANCH_LIST_SUCCESS';
export const GET_BRANCH_LIST_FAILED = 'GET_BRANCH_LIST_FAILED';

export const ADD_BRANCH_REQUESTED = 'ADD_BRANCH_REQUESTED';
export const ADD_BRANCH_SUCCESS = 'ADD_BRANCH_SUCCESS';
export const ADD_BRANCH_FAILED = 'ADD_BRANCH_FAILED';

export const DELETE_BRANCH_REQUESTED = 'DELETE_BRANCH_REQUESTED';
export const DELETE_BRANCH_SUCCESS = 'DELETE_BRANCH_SUCCESS';
export const DELETE_BRANCH_FAILED = 'DELETE_BRANCH_FAILED';

export const UPDATE_BRANCH_REQUESTED = 'UPDATE_BRANCH_REQUESTED';
export const UPDATE_BRANCH_SUCCESS = 'UPDATE_BRANCH_SUCCESS';
export const UPDATE_BRANCH_FAILED = 'UPDATE_BRANCH_FAILED';

export const ADD_QUOTATION_REQUESTED = 'ADD_QUOTATION_REQUESTED';
export const ADD_QUOTATION_SUCCESS = 'ADD_QUOTATION_SUCCESS';
export const ADD_QUOTATION_FAILED = 'ADD_QUOTATION_FAILED';